// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: proto/mathoper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение - запрос от агента на получение новой операции
type OperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // числа здесь - порядок полей в сообщении
}

func (x *OperRequest) Reset() {
	*x = OperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mathoper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperRequest) ProtoMessage() {}

func (x *OperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mathoper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperRequest.ProtoReflect.Descriptor instead.
func (*OperRequest) Descriptor() ([]byte, []int) {
	return file_proto_mathoper_proto_rawDescGZIP(), []int{0}
}

func (x *OperRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// Сообщение - арифметическая операция для выполнения агентом
type OperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId        int32  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId        int32  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Operand1      int32  `protobuf:"varint,3,opt,name=operand1,proto3" json:"operand1,omitempty"`
	Operand2      int32  `protobuf:"varint,4,opt,name=operand2,proto3" json:"operand2,omitempty"`
	Operator      string `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	OperatorDelay int32  `protobuf:"varint,6,opt,name=operator_delay,json=operatorDelay,proto3" json:"operator_delay,omitempty"`
}

func (x *OperResponse) Reset() {
	*x = OperResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mathoper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperResponse) ProtoMessage() {}

func (x *OperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mathoper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperResponse.ProtoReflect.Descriptor instead.
func (*OperResponse) Descriptor() ([]byte, []int) {
	return file_proto_mathoper_proto_rawDescGZIP(), []int{1}
}

func (x *OperResponse) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *OperResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *OperResponse) GetOperand1() int32 {
	if x != nil {
		return x.Operand1
	}
	return 0
}

func (x *OperResponse) GetOperand2() int32 {
	if x != nil {
		return x.Operand2
	}
	return 0
}

func (x *OperResponse) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OperResponse) GetOperatorDelay() int32 {
	if x != nil {
		return x.OperatorDelay
	}
	return 0
}

// Сообщение - результат выполнения арифметической операции
type OperResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId  int32  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	NodeId  int32  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Result  int64  `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	Message string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OperResultRequest) Reset() {
	*x = OperResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mathoper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperResultRequest) ProtoMessage() {}

func (x *OperResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mathoper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperResultRequest.ProtoReflect.Descriptor instead.
func (*OperResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_mathoper_proto_rawDescGZIP(), []int{2}
}

func (x *OperResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *OperResultRequest) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *OperResultRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *OperResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OperResultRequest) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OperResultRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Сообшение от агента с описанием его статуса
type AgentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId    string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status     string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalProcs int32  `protobuf:"varint,3,opt,name=total_procs,json=totalProcs,proto3" json:"total_procs,omitempty"`
	IdleProcs  int32  `protobuf:"varint,4,opt,name=idle_procs,json=idleProcs,proto3" json:"idle_procs,omitempty"`
	Verbose    string `protobuf:"bytes,5,opt,name=verbose,proto3" json:"verbose,omitempty"`
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mathoper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mathoper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusRequest.ProtoReflect.Descriptor instead.
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mathoper_proto_rawDescGZIP(), []int{3}
}

func (x *AgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatusRequest) GetTotalProcs() int32 {
	if x != nil {
		return x.TotalProcs
	}
	return 0
}

func (x *AgentStatusRequest) GetIdleProcs() int32 {
	if x != nil {
		return x.IdleProcs
	}
	return 0
}

func (x *AgentStatusRequest) GetVerbose() string {
	if x != nil {
		return x.Verbose
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mathoper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mathoper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mathoper_proto_rawDescGZIP(), []int{4}
}

var File_proto_mathoper_proto protoreflect.FileDescriptor

var file_proto_mathoper_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x6f, 0x70, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x61, 0x74, 0x68, 0x6f, 0x70, 0x65, 0x72,
	0x22, 0x28, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x0c, 0x4f,
	0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x65,
	0x6c, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0xaa, 0x01, 0x0a, 0x11, 0x4f, 0x70, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x63, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0xc2, 0x01, 0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x72, 0x12, 0x15,
	0x2e, 0x6d, 0x61, 0x74, 0x68, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x6f, 0x70, 0x65, 0x72,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0a, 0x4f, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x2e, 0x6d, 0x61,
	0x74, 0x68, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x6f,
	0x70, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3c, 0x0a, 0x0b, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x6f,
	0x70, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x61, 0x74, 0x68, 0x6f, 0x70, 0x65,
	0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x75, 0x72, 0x34, 0x36, 0x36, 0x2f, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mathoper_proto_rawDescOnce sync.Once
	file_proto_mathoper_proto_rawDescData = file_proto_mathoper_proto_rawDesc
)

func file_proto_mathoper_proto_rawDescGZIP() []byte {
	file_proto_mathoper_proto_rawDescOnce.Do(func() {
		file_proto_mathoper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mathoper_proto_rawDescData)
	})
	return file_proto_mathoper_proto_rawDescData
}

var file_proto_mathoper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_mathoper_proto_goTypes = []interface{}{
	(*OperRequest)(nil),        // 0: mathoper.OperRequest
	(*OperResponse)(nil),       // 1: mathoper.OperResponse
	(*OperResultRequest)(nil),  // 2: mathoper.OperResultRequest
	(*AgentStatusRequest)(nil), // 3: mathoper.AgentStatusRequest
	(*Empty)(nil),              // 4: mathoper.Empty
}
var file_proto_mathoper_proto_depIdxs = []int32{
	0, // 0: mathoper.MathOperService.Oper:input_type -> mathoper.OperRequest
	2, // 1: mathoper.MathOperService.OperResult:input_type -> mathoper.OperResultRequest
	3, // 2: mathoper.MathOperService.AgentStatus:input_type -> mathoper.AgentStatusRequest
	1, // 3: mathoper.MathOperService.Oper:output_type -> mathoper.OperResponse
	4, // 4: mathoper.MathOperService.OperResult:output_type -> mathoper.Empty
	4, // 5: mathoper.MathOperService.AgentStatus:output_type -> mathoper.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mathoper_proto_init() }
func file_proto_mathoper_proto_init() {
	if File_proto_mathoper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mathoper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mathoper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mathoper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mathoper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mathoper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mathoper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mathoper_proto_goTypes,
		DependencyIndexes: file_proto_mathoper_proto_depIdxs,
		MessageInfos:      file_proto_mathoper_proto_msgTypes,
	}.Build()
	File_proto_mathoper_proto = out.File
	file_proto_mathoper_proto_rawDesc = nil
	file_proto_mathoper_proto_goTypes = nil
	file_proto_mathoper_proto_depIdxs = nil
}
